roles:
  - name: airflow_orchestrator

warehouses:
  - name: airflow_orchestrator

users:
  - name: srv_airflow
    type: legacy_service

grants:
  - role: airflow_orchestrator
    warehouses:
      - airflow_orchestrator
    to_users:
      - srv_airflow
