version: "1.0"

# Roles
roles:
  - airflow_transformer:
      member_of:
        - regnskap_transformer
        - faktura_transformer
        - eiendom_transformer
      warehouses:
        - airflow_transformer
  - airflow_orchestrator:
      member_of:
        - regnskap_transformer
        - regnskap_loader
        - faktura_transformer
        - faktura_loader
        - eiendom_transformer
        - eiendom_loader

  - reporting_airflow:
      member_of:
        - reporting_microstrategy
        - okonomimodell_reporter
      warehouses:
        - reporting_airflow
      owner: useradmin

users:
  - srv_airflow_reader:
      can_login: yes
      member_of:
        - reporting_airflow
  - srv_airflow_transformer:
      can_login: yes
      member_of:
        - airflow_transformer
  - srv_airflow:
      can_login: yes
      member_of:
        - airflow_orchestrator

# Warehouses to be created
warehouses:
  - airflow_transformer:
      size: x-small

  - reporting_airflow:
      size: x-small
