version: "1.0"

# Roles
roles:
  - airflow_transformer:
      member_of:
        - regnskap_transformer
        - faktura_transformer
      warehouses:
        - airflow_transformer

  - reporting_airflow:
      member_of:
        - reporting_microstrategy
      warehouses:
        - reporting_airflow
      owner: useradmin

users:
  - srv_airflow_reader:
      can_login: yes
      member_of:
        - reporting_airflow
  - srv_airflow_transformer:
      can_login: yes
      member_of:
        - airflow_transformer

# Warehouses to be created
warehouses:
  - airflow_transformer:
      size: x-small

  - reporting_airflow:
      size: x-small
